#!/usr/bin/env node
/**
 * graphify: builds a module-dependency graph for notes-tasks by statically
 * parsing require()/import specifiers under backend/src and frontend/src.
 * Zero third-party dependencies (Node builtins only) so it runs anywhere.
 *
 * Usage: node .claude/skills/graphify/scripts/generate-graph.js [--out <file>]
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..', '..');
const OUT_ARG_INDEX = process.argv.indexOf('--out');
const OUT_FILE = OUT_ARG_INDEX !== -1
  ? path.resolve(ROOT, process.argv[OUT_ARG_INDEX + 1])
  : path.join(ROOT, 'docs', 'CODEBASE_GRAPH.md');

const SKIP_DIRS = new Set(['node_modules', '.git', 'dist', 'build', '.svelte-kit', 'coverage']);

/** @type {{root: string, exts: string[], alias?: {from: string, to: string}}[]} */
const SCAN_TARGETS = [
  { app: 'backend', root: path.join(ROOT, 'backend', 'src'), exts: ['.js'] },
  {
    app: 'frontend',
    root: path.join(ROOT, 'frontend', 'src'),
    exts: ['.ts', '.svelte'],
    alias: { from: '$lib', to: path.join(ROOT, 'frontend', 'src', 'lib') },
  },
];

function walk(dir, exts, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, exts, out);
    } else if (exts.includes(path.extname(entry.name)) && !entry.name.endsWith('.test.ts')) {
      out.push(full);
    }
  }
  return out;
}

// require(...), import ... from '...', export ... from '...', dynamic import('...')
const SPEC_RE = /(?:require\(\s*|(?:import|export)(?:[^'";]*?)from\s*|import\(\s*)['"]([^'"]+)['"]\s*\)?/g;

function extractSpecifiers(source) {
  const specs = [];
  let m;
  SPEC_RE.lastIndex = 0;
  while ((m = SPEC_RE.exec(source))) specs.push(m[1]);
  return specs;
}

function resolveSpecifier(spec, fromFile, target) {
  let base;
  if (spec.startsWith('.')) {
    base = path.resolve(path.dirname(fromFile), spec);
  } else if (target.alias && spec.startsWith(target.alias.from)) {
    base = target.alias.to + spec.slice(target.alias.from.length);
  } else {
    return null; // external package / framework import — not part of the internal graph
  }
  const candidates = [
    base,
    ...target.exts.map((e) => base + e),
    ...target.exts.map((e) => path.join(base, 'index' + e)),
  ];
  return candidates.find((c) => fs.existsSync(c) && fs.statSync(c).isFile()) || null;
}

function layerOf(file, target) {
  const rel = path.relative(target.root, file);
  const segments = rel.split(path.sep);
  if (target.app === 'backend') {
    return segments.length > 1 ? segments[0] : 'entry';
  }
  // frontend: src/lib/<layer>/... or src/routes/...
  if (segments[0] === 'routes') return 'routes';
  if (segments[0] === 'lib' && segments.length > 1) return segments[1];
  return 'entry';
}

function shortName(file) {
  return path.relative(ROOT, file).replace(/\\/g, '/');
}

function buildGraph(target) {
  const files = walk(target.root, target.exts);
  const nodes = new Map(); // file -> layer
  const edges = []; // {from, to, fromLayer, toLayer}
  const importCount = new Map(); // file -> number of times imported (fan-in)

  for (const file of files) nodes.set(file, layerOf(file, target));

  for (const file of files) {
    const source = fs.readFileSync(file, 'utf8');
    const specs = extractSpecifiers(source);
    for (const spec of specs) {
      const resolved = resolveSpecifier(spec, file, target);
      if (!resolved || !nodes.has(resolved) || resolved === file) continue;
      edges.push({ from: file, to: resolved, fromLayer: nodes.get(file), toLayer: nodes.get(resolved) });
      importCount.set(resolved, (importCount.get(resolved) || 0) + 1);
    }
  }

  return { files, nodes, edges, importCount };
}

function layerGraphMermaid(target, graph) {
  const layerEdges = new Map(); // "a->b" -> count
  let intraLayer = 0;
  for (const e of graph.edges) {
    if (e.fromLayer === e.toLayer) {
      intraLayer++;
      continue;
    }
    const key = `${e.fromLayer}|${e.toLayer}`;
    layerEdges.set(key, (layerEdges.get(key) || 0) + 1);
  }

  const lines = [`flowchart LR`];
  for (const [key, count] of layerEdges) {
    const [a, b] = key.split('|');
    lines.push(`    ${a}["${a}"] -->|${count}| ${b}["${b}"]`);
  }
  return { mermaid: lines.join('\n'), intraLayer };
}

function topHubs(graph, n = 8) {
  return [...graph.importCount.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([file, count]) => `- \`${shortName(file)}\` — imported by ${count} module${count === 1 ? '' : 's'}`);
}

function render() {
  const sections = [];
  sections.push('# Codebase Dependency Graph\n');
  sections.push(
    '_Generated by `.claude/skills/graphify` — a static import/require scan of `backend/src` and `frontend/src`. ' +
    'Re-run `node .claude/skills/graphify/scripts/generate-graph.js` after structural changes; this file is not watched automatically._\n'
  );

  for (const target of SCAN_TARGETS) {
    const graph = buildGraph(target);
    const { mermaid, intraLayer } = layerGraphMermaid(target, graph);

    sections.push(`## ${target.app}\n`);
    sections.push(`${graph.files.length} files scanned, ${graph.edges.length} internal import edges found (${intraLayer} within the same layer, omitted from the diagram below for readability).\n`);
    sections.push('```mermaid\n' + mermaid + '\n```\n');
    sections.push('**Most-depended-on files** (read these first — changing them has the widest blast radius):\n');
    sections.push(topHubs(graph).join('\n') + '\n');
  }

  sections.push('## How this was built\n');
  sections.push(
    'The generator resolves relative (`./`, `../`) and `$lib/...` specifiers to real files via `require()`/`import ... from`/`export ... from`/dynamic `import()` regex extraction — no bundler, no execution. ' +
    'It intentionally ignores bare-specifier imports (npm packages, `svelte/store`, `$app/*`, etc.) since those are external to this repo\'s own module graph. ' +
    'Edges between `frontend` and `backend` are never inferred here because the two are separate npm projects that only talk over HTTP — see `frontend/src/lib/api/client.ts` and `backend/src/routes/` for that boundary.'
  );

  return sections.join('\n');
}

const output = render();
fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, output);
console.log(`Wrote ${path.relative(ROOT, OUT_FILE)}`);
